### ISSUE TITLE
Prevent click propagation on drag and drop 

### ISSUE THREAD

**Issue by stvmachine** [davidsa/drag-scroll-provider#14]
I was wondering if anyone had an issue with click event being fired after drag and drop.

Is there an easy way to prevent this from happening?

**Comment by stvmachine** [comment]
So, my solution was:

```javascript

componentDidMount(){
   ....
   this.addEventListenerWithClear("click", this.handleOnClick);
}

 handleOnClick = e => {
    const { time } = this.privateState;
    if (!time || time > this.threshold) {
      if (e.stopPropagation) e.stopPropagation();
      if (e.preventDefault) e.preventDefault();
      e.cancelBubble = true;
      e.returnValue = false;
      return false;
    }
  };

```

**Comment by davidsa** [comment]
hey @stvmachine sorry for not responding in a long time, for some reason i didn't get an email from this, did you solve this issue? are you using the `clickItem` callback ?
